export const ON_CHANGE_TEXT = 'ON_CHANGE_TEXT'
export const ON_CHANGE_DATE = 'ON_CHANGE_DATE'
export const GALERY_SAVE = 'SAVE_ON_CLICK'
export const CLEAR_FORM = 'CLEAR_FORM'
export const GALERY_EDITOR_ENABLE= 'GALERY_EDITOR_ENABLE'
export const GALERY_DELETE= 'GALERY_DELETE'
export const MODAL_OPEN= 'MODAL_OPEN'
export const MODAL_CLOSE= 'MODAL_CLOSE'
export const GALERIES_LIST_SYNC= 'GALERY_LIST_SYNC'
export const GET_PROCESSING_NAME= 'GALERY_LIST_SYNC'
export const ADD_IMAGES_TO_GALERY= 'ADD_IMAGES_TO_GALERY'
export const DISPLAY_IMAGE_TO_MAIN_SCREEN = 'DISPLAY_IMAGE_TO_MAIN_SCREEN'
export const SET_GALERY_MAIN_IMAGE = 'SET_GALERY_MAIN_IMAGE'




